### ISSUE TITLE
Robotdyn Uno WiFi R3: ESP8266 - SD card fails when WiFi is connected

### ISSUE THREAD

**Issue by marcrdavis** [JAndrassy/WiFiEspAT#100]
Hi - having an issue with the library on a Robotdyn Uno WiFi R3: ESP8266 board. Wifi by itself works fine; SD card by itself works fine. After Wifi has made a client connection the SD card is unable to assert itself on the SPI bus (Wifi and SD have different cs pins). Not seeing this problem on the SONGHE MEGA2560 + WIFI R3 (ESP8266). Thought it might be bad hardware but it is failing the same way on multiple boards. If I switch the Wifi Library to WifiESP (AT Version) the SD card works (but I am not a fan of the performance of this library). 

Any thoughts on what could be going wrong or how to fix? Thanks!

Marc

**Comment by JAndrassy** [comment]
it is the problem with the available SRAM. the SD library needs a 512 bytes buffer of 2kB. the WiFiEspAT library allocates at runtime at least two 32 bytes buffers.
