### ISSUE TITLE
WiFiWebServer.h: No such file or directory

### ISSUE THREAD

**Issue by hilmiyafia** [JAndrassy/WiFiEspAT#108]
I tried running the HelloServer example on my Arduino Mega, but this error came up at compilation:

WiFiWebServer.h: No such file or directory

**Comment by JAndrassy** [comment]
sorry, then I thought the WiFiWebServer library would become well known. 
![Screenshot from 2023-06-10 15-04-56](https://github.com/JAndrassy/WiFiEspAT/assets/10706773/4b283f69-4ceb-4149-94b2-22711d2525d7)

**Comment by hilmiyafia** [comment]
@JAndrassy Thank you for the reply, but now I have this error:

![Screenshot 2023-06-11 061858](https://github.com/JAndrassy/WiFiEspAT/assets/56539775/e4343d69-1e2b-492a-a6e5-0dcaad7b6a01)

**Comment by JAndrassy** [comment]
it was working on Mega then. now it looks like there is some incompatibility in the WiFiWebServer library. try older versions of the  WiFiWebServer library

**Comment by hilmiyafia** [comment]
@JAndrassy Ok thank you, the latest version that works is 1.4.2 😊
