### ISSUE TITLE
startMDNS stops after 5min (TTL 300)

### ISSUE THREAD

**Issue by pchar** [jandrassy/WiFiEspAT#13]
Hi,
I notice that startMDNS stops after 5 minutes and after there's no way to status it again 
did you know how to restart the mDNS responder ?

**Comment by jandrassy** [comment]
are you on latest firmware version? try the command without the library. if it fails, you can report the problem to Espressif

**Comment by pchar** [comment]
yes the latest 

AT firmware version 1.7.2.0
AT firmware is OK for the WiFiEspAT library.


yes seams that fails also with a direct command
