### ISSUE TITLE
Handling the payload of POST requests 

### ISSUE THREAD

**Issue by vtolenti89** [jandrassy/WiFiEspAT#15]
I am currently using the ESP8266 to handle requests from a mobile app.
The `GET` requests work flawlesly, but I am having a tough time trying to process the payload of POST requests. 
I have checked the source code thoroughly, and I came up with the following:

```
if (buf.endsWith("GET /light/status")) {
          Serial.println("...Getting light status");
          getLightStatus();
        }
        else if (buf.endsWith("POST /light/set")) {
          Serial.println("...POST:");
        while(client.available() && client.peek()) {
                Serial.write(client.read());
            }
```
This code shows the header and the payload in the serial monitor, and then hangs. It seems, that even though the client.read() is not returning anything anymore, the while condition is still true.

Any idea what might've gone wrong?

Furtheremore, is there an easier way of processing the payload information. In my case it would look like the following
```
{
 {
   pin: 1,
   status: true
 },
{
   pin: 2,
   status: false
 },
}
```
and then it would be processed by the MCU and used to control its pins.

Thanks .

**Comment by jandrassy** [comment]
https://www.arduino.cc/reference/en/language/functions/communication/stream/streampeek/
