### ISSUE TITLE
send a message to the client on connection

### ISSUE THREAD

**Issue by atesin** [jandrassy/WiFiEspAT#22]
i want to send a welcome/status/notifications/motd message when client connects without client have to send anything... 

with server.available() i got the client object but just when it sends something... so i cannot send "pushes" but just responses

**Comment by atesin** [comment]
nevermind...  i can use server.accept() like shown in AdvancedChatServer.ino example

i was confused because the function is not present in WiFiNINA api

**Comment by jandrassy** [comment]
https://github.com/jandrassy/WiFiEspAT#the-wifiserver-class-differences
