### ISSUE TITLE
WiFi.macAddress() not supported in JB 1.7 firmware

### ISSUE THREAD

**Issue by iactiva** [jandrassy/WiFiEspAT#32]
Just noticed WiFi.macAddress() is not working with [Jiri Bilek firmware 1.7](https://github.com/JiriBilek/ESP_ATMod#description) as AT command AT+CIPSTAMAC? is not supported.

As command AT+CIFSR is still working, I have done a quick temporary fix to function [staMacQuery()](https://github.com/jandrassy/WiFiEspAT/blob/3ba2e69385a844ee78d498bb8f6edec2fb2c6f5e/src/utility/EspAtDrv.cpp#L292) in [utility/EspAtDrv.cpp](https://github.com/jandrassy/WiFiEspAT/blob/master/src/utility/EspAtDrv.cpp).

```
bool EspAtDrvClass::staMacQuery(uint8_t* mac) {
  maintain();

  LOG_INFO_PRINT_PREFIX();
  LOG_INFO_PRINTLN(F("STA MAC query "));

  cmd->print(F("AT+CIFSR"));
  if (!sendCommand(PSTR("+CIFSR")))
    return false;
  const char* delims = ":\"";
  char* tok = strtok(buffer, delims); //+CIFSR:STAMAC,"
  for (int i = 6; i >= 0; i--) {
    tok = strtok(NULL, delims); // <mac>[i]
    mac[i] = strtol(tok, NULL, 16);
  }
  return readOK();
}
```

**Comment by jandrassy** [comment]
the firmware is an Arduino sketch. you can add the command there
