### ISSUE TITLE
WiFi Web Server with AT version 2.2.0.0-dev

### ISSUE THREAD

**Issue by f4goh** [jandrassy/WiFiEspAT#37]
Hello,
I try to use WiFi Web Server with AT version 2.2.0.0-dev
i comment //#define WIFIESPAT1 in EspAtDrvTypes.h
PrintPersistentSettings.ino works, i can connect to my wifi access point
But when i use WebServer.ino exemple after
the connection reset and the web page doesn't appairs
          client.flush();
          delay(1000);
i need to add delay afer flush to solve the problem

The AT version 1.7 works well , but need MQTT and HTML at commands too with version 2.2.0.0

Here is the serial outpout, i add a 
Serial.println(line.length()); to see what's happend

Thanks and HNY
Anthony

```
Waiting for connection to WiFi


Connected to WiFi network.
To access the server, enter "http://192.168.1.32/" in web browser.
new client 192.168.1.13
GET / HTTP/1.1
14
Host: 192.168.1.32
18
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
89
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
82
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
52
Accept-Encoding: gzip, deflate
30
Connection: keep-alive
22
Upgrade-Insecure-Requests: 1
28

0->send page
client disconnected
```

**Comment by jandrassy** [comment]
please turn on debug level, to see the AT commands and responses
https://github.com/jandrassy/WiFiEspAT#logging
