### ISSUE TITLE
Update  remote database Xamp server

### ISSUE THREAD

**Issue by sgamoct** [jandrassy/WiFiEspAT#39]
Hi, I am trying to insert data on a remote database which is built on xamp.
unfortunately I can't write these two data. I'm going crazy I don't understand where the problem is. 
the wifi is connected and from the pc or mobile phone connected to the same network I can write and read the database.
this is my code:

```
   #include` <WiFiEspAT.h>       
   #include <WiFiClient.h> 
    #include "WiFi.h"           
 void setup() {   
    Serial.begin(115200);         
    while (!Serial);                 
    Serial1.begin(115200);          
    WiFi.init(Serial1);
    WiFiClient client;          
    WiFi.endAP(true);             
    WiFi.disconnect();     
    delay(100);                
    WiFi.setPersistent();     
    int status = WiFi.begin(ssid, pass);
}
 void loop() {
  WiFiClient  client;
  String strURL ="GET 192.168.0.131/sudatabase/admin/system/functions.php?Red=xyz&H=69 HTTP/1.1";
  client.println (strURL);
  client.println("Connection: close");
  client.println();
  client.stop();
  delay (5000);
  Serial.println("inviato");
  }
```

the server has a local address of 192.168.0.131 and is installed on xampp and can be reached by other devices, the two parameters to be sent are Red and H.
can you help me to solve this problem?

**Comment by jandrassy** [comment]
see the WiFiClient example

**Comment by sgamoct** [comment]
> guarda l'esempio WiFiClient

WebClient?

**Comment by jandrassy** [comment]
> > guarda l'esempio WiFiClient
> 
> WebClient?

sorry, yes, WebClient

**Comment by sgamoct** [comment]
Ok i try it.
thankyou

**Comment by sgamoct** [comment]
Happy, work fine!
thankyou
