### ISSUE TITLE
undefined reference to `typeinfo for arduino::Print'

### ISSUE THREAD

**Issue by Dracanrage** [jandrassy/WiFiEspAT#41]
When I try to define variable of class WiFiClient, it shows undefined reference to `typeinfo for arduino::Print'.
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/30333935/111468253-4fc73e80-8760-11eb-9506-056f4e544e98.png">

**Comment by jandrassy** [comment]
it is an Arduino library

**Comment by Dracanrage** [comment]
> it is an Arduino library

Yes, I used this library, it seems works well without use WiFiEspAT Lib, but I don't know why it turns wrong when I try to compile it through CMake (I used VSCode).

**Comment by jandrassy** [comment]
WiFiEspAT is an Arduino library. it requires an Arduino core for the selected MCU architecture.  it is intended to be build by Arduino builder
