### ISSUE TITLE
Disable AP mode

### ISSUE THREAD

**Issue by gimenezfrg** [jandrassy/WiFiEspAT#49]
Hi, I'm using this library to connect over a wifi network and send data to an API, everything works fine.

The question is that I realized that ESP is active as if it were a router too, that is, if I look at the available wireless networks the ESP appears, I would like to disable it, is there how?

**Comment by jandrassy** [comment]
see the Tools section of WiFiEspAT examples in Arduino IDE Examples menu

**Comment by gimenezfrg** [comment]
I can connect and use normally, I just wish it didn't appear as a network, I would like to disable this function if possible.

![image](https://user-images.githubusercontent.com/13823246/123143060-80d69f80-d430-11eb-9407-169d83ee2e3b.png)

![image](https://user-images.githubusercontent.com/13823246/123142980-67cdee80-d430-11eb-8d17-49bdc1a97d46.png)

![image](https://user-images.githubusercontent.com/13823246/123142854-466d0280-d430-11eb-9cb2-3fa8f32cdfb8.png)

**Comment by gimenezfrg** [comment]
I think I understand, I put these three lines before BEGIN:

```
  WiFi.disconnect(); // to clear the way. not persistent
  WiFi.setPersistent(); // set the following WiFi connection as persistent
  WiFi.endAP(); // to disable default automatic start of persistent AP at startup
```

Is correct?

**Comment by jandrassy** [comment]
I don't remember the details, but here is the doc:
https://github.com/jandrassy/WiFiEspAT#the-wifi-object-differences
