### ISSUE TITLE
Problems with SNTPTime example

### ISSUE THREAD

**Issue by DavidMR91** [jandrassy/WiFiEspAT#55]
Hello, I'm having this problem with the SNTPTime example:

```
Waiting for connection to WiFi
.
Waiting for SNTP
............................................................................................................................................................................................................................
```

**Comment by jandrassy** [comment]
as documented in firmware compare table in README and in the comment on top of the example, getTime doesn't work with Espressif AT 1

**Comment by DavidMR91** [comment]
My esp8266 have the Espressif AT firmware 2.1 downloaded since https://github.com/jandrassy/UnoWiFiDevEdSerial1/wiki/files/ESP8266-1MB-tx1rx3-AT_V2.1.zip and uploaded with esptool.py

**Comment by DavidMR91** [comment]
fixed, I forgot to comment #define WIFIESPAT1 in Documents\Arduino\libraries\WiFiEspAT\src\utility\EspAtDrvTypes.h
