### ISSUE TITLE
AT Firmware 2.1 for ESP8266 version Issue

### ISSUE THREAD

**Issue by DavidMR91** [jandrassy/WiFiEspAT#56]
Hello, 
After downloading https://github.com/jandrassy/UnoWiFiDevEdSerial1/wiki/files/ESP8266-1MB-tx1rx3-AT_V2.1.zip and uploading it to the ESP8266 using esptool.py, appears like v2.2 not v2.1:
![image](https://user-images.githubusercontent.com/7366359/126094155-df221751-63f4-4528-ae46-017c329eda13.png)

![image](https://user-images.githubusercontent.com/7366359/126094048-ccc7bee0-f25e-43fe-b23d-78ccd9af327f.png)

**Comment by jandrassy** [comment]
yes. but it is 2.1

**Comment by DavidMR91** [comment]
Why if I download, compile and upload the V2.1 if I run the firmware version checker, say V2.2.0.0-dev?
I'm trying to downgrade the AT Firmware, and every time apear V2.2.0.0-dev. The firmware is loading correctly, and I tried to upload a blank sketch and then the AT Firmware 2.1 and V2.2.0.0-dev still appears

**Comment by jandrassy** [comment]
because I built the 1 MB version after they changed the version number, but before any other changes. with AT+GMR you can see that the build timestamp is from last year
