### ISSUE TITLE
AT Firmware 2.2 OTA problems

### ISSUE THREAD

**Issue by DavidMR91** [jandrassy/WiFiEspAT#57]
Hello,
The last few weeks I have been playing and working with SerialWiFiOTA with AT Firmware 2.1 on ESP8266 and with an ATMega 2560 with communication between them at 250,000 baud.
With this configuration, everything worked perfect, but when uploading AT Firmware 2.2, it seems that it has stopped working. I attach a photo:
![image](https://user-images.githubusercontent.com/7366359/126096710-bed17430-374b-44c1-aae4-f87abde2d941.png)
Do you know what could be happening?

**Comment by jandrassy** [comment]
everything else works with AT 2.2? only upload doesn't?

**Comment by DavidMR91** [comment]
Right, the rest of things seem to work all

**Comment by DavidMR91** [comment]
Sorry, my fault, I changed computers and I forgot a step:
I forgot to copy file "platform.local.txt" from "C:\Users\[USER]\Documents\Arduino\libraries\ArduinoOTA\extras\avr" to "C:\Program Files (x86)\Arduino\hardware\arduino\avr"

**Comment by jandrassy** [comment]
now I see that it used the old upload command version
