### ISSUE TITLE
esp8266 1M AT 2 binaries

### ISSUE THREAD

**Issue by jondurrant** [jandrassy/WiFiEspAT#64]
Thank you for the esp8266 1M AT 2 binaries.

On an ESP-01S I can only get 2.1 binary to run and it identifies itself as 2.2! The 2.2 binary does not respond to AT commands, even if I replace the factory_param file.

Could you confirm is the 2.1 archive a 2.2 build?

**Comment by jandrassy** [comment]
sorry no idea. for me it works on a 1 MB Wemos D1 mini light
