### ISSUE TITLE
Software reset

### ISSUE THREAD

**Issue by bobemoe** [jandrassy/WiFiEspAT#66]
Is a software reset possible?

I know I can do hardware reset by passing pin to `.reset()` and to `.init()` but wondering if a software reset is supported? 

I can only find reference to hw reset in docs and examples.

Thanks for the awesome library :)

**Comment by jandrassy** [comment]
WiFi.reset(-1) does a software reset. I should set it as a default value for the parameter.

**Comment by bobemoe** [comment]
Perfect, thanks. Default value sounds like a good idea.

**Comment by jandrassy** [comment]
WiFi.reset() in 1.3.2
