### ISSUE TITLE
Stop client.connect() from blocking

### ISSUE THREAD

**Issue by bobemoe** [jandrassy/WiFiEspAT#67]
I'm trying to make my code more robust on an unreliable internet connection.

If the wifi is connected but the internet is not available, `client.connect()` can block for 15 seconds.

Is it possible to set a custom timeout? Similar to what was done here https://github.com/espressif/arduino-esp32/pull/2606

Or use a callback maybe so other code can continue to execute?

**Comment by jandrassy** [comment]
AT firmware doesn't support timeout for AT+CIPSTART and no other command can be run until the current AT command finishes. the library must wait for the response to the AT command.
