### ISSUE TITLE
'Stream' has not been declared

### ISSUE THREAD

**Issue by stepanurban** [jandrassy/WiFiEspAT#7]
Hi,
I'm getting following error when trying to compile ScanNetworksAdvanced example for Arduino nano 33
/home/.../Arduino/libraries/WiFiEspAT/src/utility/EspAtDrvTypes.h:61:30: error: 'Stream' has not been declared
virtual uint8_t readRxData(Stream* serial, size_t len) = 0;

Where is the problem? How to get it?
Thank you

**Comment by jandrassy** [comment]
Nano 33 BLE? Sorry I didn't test with it yet even I have it.
add `#include <Arduino.h>` at the beginning of `WiFiEspAT/src/utility/EspAtDrvTypes.cpp`
