### ISSUE TITLE
[question] which ssid is my esp currently connected?

### ISSUE THREAD

**Issue by atesin** [jandrassy/WiFiEspAT#70]
hi.....  i have some esp8266 with join remote ap persistent on its own flash, not set by me

is there any way to find which ssid are esp's currently connected??... like the `WiFi.localIP()` function that tells the station ip assigned by ap dhcp, but a command to tell  the actual name of external ap.... i have many wifis surrounding, i need this function to know which wifi connect my devices to reach the esp (imagine ssid and ip will be printed on an lcd)

with direct AT commands i can send  `AT+CWJAP_CUR?` to know the ssid of remote ap which connected in realtime, but i am asking for an equivalent in this library.... i couldn't found any reference on documentation

**Comment by atesin** [comment]
i answer myself... accordig the `PrintPersistentSettings,ino` example, the function seems to be `WiFi.SSID(charBuffer)` which puts the currently connected ap ssid in char buffer...  this differs a little from wifinina api, this only works on curently connected wifi ans is reentrant

not tested yet... any additional comment? ..  thanks

**Comment by jandrassy** [comment]
https://github.com/jandrassy/WiFiEspAT#enhanced-wifi-api

> SSID optionally can be called with char array to fill (see PrintPersistentSettings.ino tool example)

the WiFiNINA way works too
