### ISSUE TITLE
cannot set softap persistent

### ISSUE THREAD

**Issue by atesin** [JAndrassy/WiFiEspAT#77]
hi... in my sketch i have these commands (i previously configured ap parameters)
```
  WiFi.setPersistent();
  WiFi.beginAP();
```
everything is fine, i can detect the wifi with my phone and can connect with my parameters... then as the configurarion is stored in the esp i commented these lines and reflash the sketch

but if i hard-reset the arduino+esp reconnecting power the wifi was gone... so i repeat the process with logging enabled and that is what i saw
```
esp INFO: begin SoftAP persistent
esp> AT+CWMODE_CUR=3 ...sent
esp> OK ...matched
```
i believe for persistent mode the command should be `AT+CWMODE_DEF=3` instead the `_CUR`one ... furthermore i grepped the `_DEF` string in all files and just found 2 lines in `EspAtDrv.cpp` referencing `AT+CIPDNS_DEF` command, nothing more...  there are many persistent commands ended with `_DEF` present in my firmware, it is based on espressif nonos sdk ver 3.0.1 (at v1.7 custom)

[lobo AT reference documentation](https://github.com/loboris/ESP8266_AT_LoBo/blob/master/at_lobo/doc/4a-esp8266_at_instruction_set_en.pdf)

i have LoBo firmware and esp-01s (the tiny black 2x4 pins 2 chips esp with 1M flash), because espressif firmware didn't support passive mode transfer for 1mb chips
![esp-01s](https://cdn.shopify.com/s/files/1/1619/4791/products/1_db64df40-1824-4594-bb43-b54ddae2fa8b_compact.jpg)

**Comment by JAndrassy** [comment]
without _DEF it is same as _DEF in AT 1.
I will check the softAP persistence

**Comment by JAndrassy** [comment]
SoftAP mode is not made persistent. the SoftAP settings are persistent

**Comment by atesin** [comment]
> SoftAP mode is not made persistent. the SoftAP settings are persistent. you can use WiFi.beginAP() without parameters to start the SoftAP with persistent settings.

and how about `AT+CWMODE_DEF=3` or 2 ??

![image](https://user-images.githubusercontent.com/8086106/165854801-e221d1cf-053e-4cdc-8b7b-fedd6081902c.png)
![image](https://user-images.githubusercontent.com/8086106/165854920-f00fc405-5c61-4f9e-9461-a566f4d05b21.png)

![image](https://user-images.githubusercontent.com/8086106/165855320-c9506fa0-4be0-400b-b39d-eb6d48d5820e.png)
![image](https://user-images.githubusercontent.com/8086106/165855103-a5b07dfd-4b9f-4fb5-9eef-23d551876020.png)
![image](https://user-images.githubusercontent.com/8086106/165855251-dbe010d1-376c-4fa6-a9a1-0069728807c8.png)

**Comment by JAndrassy** [comment]
beginAP doesn't change remembered CWMODE. I decided that when I was creating the library.

**Comment by atesin** [comment]
sorry for post before closing .....  that means that if i set `AT+CWMODE_DEF` externally (with an ftdi and AT commands for example), this lib will never overwrite that configuration *stored on the flash* ??  
good to know it

**Comment by JAndrassy** [comment]
> sorry for post before closing ..... that means that if i set `AT+CWMODE_DEF` externally (with an ftdi and AT commands for example), this lib will never overwrite that configuration _stored on the flash_ ?? good to know it

I think, it will overwrite CWMODE_DEF if WiFi.begin is called with persistent true.
