### ISSUE TITLE
fatal error: string: No such file or directory

### ISSUE THREAD

**Issue by Vovanchik** [JAndrassy/WiFiEspAT#81]
When I am using this example:
https://github.com/JAndrassy/WiFiEspAT/blob/b9443b2142ec07847d17efe4ebbe7a5f1808b1a7/examples/Advanced/HelloServer/HelloServer.ino#L20

I am receiving the following errors during compilation on Arduino Nano:
libraries/WiFiWebServer/src/WiFiWebServer.hpp:297:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.

**Comment by JAndrassy** [comment]
https://github.com/khoih-prog/WiFiWebServer#currently-supported-boards
