### ISSUE TITLE
EspAtDrv.sntpTime() is NOT compatible with AT ver 1.7.5

### ISSUE THREAD

**Issue by maqsudbek** [JAndrassy/WiFiEspAT#93]
In the AT instruction set of ESP (non-os sdk ver 3.0.5), getting time data is done through:

AT+CIPSNTPTIME?

command, and the response looks like this:

+CIPSNTPTIME:Fri Nov 04 15:00:22 2022

Can you please fix that as well ?

Thanks in advance!

**Comment by JAndrassy** [comment]
it is documented that it doesn't work
https://github.com/JAndrassy/WiFiEspAT#capabilities-comparison
